openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: 노트(메모) 앱 RESTful API

tags:
  - name: Notes
    description: 노트 관련 API

paths:
  /notes:
    post:
      tags: [Notes]
      summary: 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteInput"
      responses:
        "201":
          description: 노트 생성 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
    get:
      tags: [Notes]
      summary: 모든 노트 목록 조회
      responses:
        "201":
          description: 노트 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Note"

  /notes/{tag}:
    get:
      tags: [Notes]
      summary: 태그로 노트 목록 조회
      parameters:
        - name: tag
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 태그별 노트 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Note"

  /notes/{id}:
    put:
      tags: [Notes]
      summary: 노트 수정
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteInput"
      responses:
        "200":
          description: 노트 수정 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
        "404":
          description: 노트 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags: [Notes]
      summary: 노트 삭제
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: 노트 삭제 성공
        "404":
          description: 노트 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    NoteInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        tag:
          type: string
      required:
        - title
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        tag:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    NoteResponse:
      type: object
      properties:
        message:
          type: string
        data:
          $ref: "#/components/schemas/Note"
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
